name: FounderHunt
version: ${project.version}
main: it.minecraft.founderhunt.FounderHunt
api-version: 1.15
softdepend: [ TecnoUtilities ]
authors: [ Dani47, zPirroZ3007 ]
description: FounderHunt Plugin
